# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
np.arange(4.0)

array([0., 1., 2., 3.])

In [5]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((2,5,))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.linspace(0,20,5)  ### here 5 means total 5 outputs with equal space 

array([ 0.,  5., 10., 15., 20.])

In [12]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.eye(5)   ### Identity matrix of 5*5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.eye(7,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [15]:
np.random.rand(2,5)  ### giving 2 rows and 5 columns of  random numbers between 0 and less than 1
                     ### rand gives uniform distribution 

array([[0.30182497, 0.24687317, 0.57312804, 0.66819563, 0.80958069],
       [0.209964  , 0.44834045, 0.88157796, 0.57760675, 0.04979366]])

In [16]:
np.random.randn(2,5) ### will also give negative number
                     ### randn gives normal distribution

array([[-1.38656073, -1.3080792 , -0.90493581,  0.35741112,  0.32432547],
       [-0.26759401,  1.34867723,  0.19082512, -0.04830298,  1.56751999]])

In [17]:
np.random.randint(2,10)  ### give any random number between 2 and 10 excluding 10

9

In [18]:
np.random.randint(20,56,100)    ### give any random number between 20 and 56(except 56 ) and 100 here represents total 100 numbers wiil be given

array([37, 45, 49, 48, 38, 21, 27, 26, 39, 27, 29, 37, 50, 48, 52, 21, 22,
       44, 31, 40, 20, 20, 48, 21, 47, 21, 21, 32, 45, 37, 32, 47, 34, 37,
       41, 30, 27, 40, 38, 27, 47, 20, 36, 22, 20, 45, 32, 35, 28, 47, 40,
       35, 43, 41, 45, 49, 35, 33, 28, 33, 27, 20, 33, 45, 34, 28, 52, 32,
       54, 29, 51, 26, 50, 34, 41, 31, 31, 52, 31, 35, 23, 47, 20, 45, 22,
       21, 41, 39, 25, 23, 40, 23, 39, 21, 27, 24, 44, 45, 35, 35])

In [19]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
rand_array=np.random.randint(0,100,20)
rand_array

array([32, 93, 60, 56,  1, 70, 92,  3, 74, 58, 10, 87, 53, 11, 63, 52, 80,
       30, 18, 73])

In [21]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [22]:
rand_array.min()

1

In [23]:
rand_array.argmin()   ### arg means index and here argmin means index of minimum

4

In [24]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
sample_array.shape

(30,)

In [26]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [27]:
sample_array.dtype

dtype('int32')

In [28]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
a.T ### transpose

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
b=np.random.rand(2,3)
b

array([[0.73054955, 0.36704876, 0.76028354],
       [0.97031133, 0.14936002, 0.90786378]])

In [31]:
b.T

array([[0.73054955, 0.97031133],
       [0.36704876, 0.14936002],
       [0.76028354, 0.90786378]])

In [32]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
sample_array[8]    # Retrieve using index

18

In [34]:
sample_array[2:5]  # Slicing 

array([12, 13, 14])

In [35]:
sample_array[2:5]=100   # Mutataion is possible
sample_array

array([ 10,  11, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [36]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [38]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [39]:
subset_sample_array[:]=1007 
subset_sample_array

array([1007, 1007, 1007, 1007, 1007, 1007, 1007])

# Two-Dimensional Array

In [40]:
sample_matrix=np.array(([1,2,3],[4,5,6],[7,8,9]))
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
sample_matrix[0][2]  # Retrieving an element

3

In [42]:
sample_matrix[2,:]  # Retrieving a row/column       # In bracket 1st element is row and 2nd is column

array([7, 8, 9])

In [43]:
sample_matrix[2]        # Not specifying column in 2d array will give row matrix only

array([7, 8, 9])

In [44]:
sample_matrix=np.array(([1,2,3],[4,5,6],[7,8,9]))
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
sample_matrix[:,(2,1)]  # Retrieving multiple rows/columns in order # Before or after column if in order written in () then will give elements order wise

array([[3, 2],
       [6, 5],
       [9, 8]])

In [46]:
sample_matrix[(2,0),:]

array([[7, 8, 9],
       [1, 2, 3]])

# Selection techniques

In [47]:
sample_array=np.arange(1,30)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [48]:
bool=sample_array<10
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [49]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [51]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12])

In [52]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481])

In [53]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583])

In [54]:
np.max(sample_array)

29

In [55]:
np.min(sample_array)

1

In [56]:
np.argmin(sample_array)

0

In [57]:
np.argmax(sample_array)

28

In [58]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841])

In [59]:
np.std(sample_array)

8.366600265340756

In [60]:
np.var(sample_array)

70.0

In [61]:
np.mean(sample_array)

15.0

In [62]:
array=np.random.randn(3,6)
array

array([[ 0.04342096,  0.04542888, -0.40920492,  0.99651662, -1.19065963,
         2.39429944],
       [-2.25182937,  1.35606871,  0.74840162, -0.67744676, -1.08726082,
         0.9403764 ],
       [-1.41339899,  0.86849209,  1.21459081,  0.37834082, -0.27790548,
        -0.95592382]])

In [63]:
np.round(array,decimals=2)

array([[ 0.04,  0.05, -0.41,  1.  , -1.19,  2.39],
       [-2.25,  1.36,  0.75, -0.68, -1.09,  0.94],
       [-1.41,  0.87,  1.21,  0.38, -0.28, -0.96]])

In [64]:
sports=np.array(["cricket","golf","cricket","football"])
np.unique(sports)

array(['cricket', 'football', 'golf'], dtype='<U8')